project_id = "mgspuayfejjwgxzzhtuw"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
external_providers = ["google", "github", "facebook", "twitter"]

[functions.create-payment]
verify_jwt = false